
### get policies from specific client
GET http://localhost:8080/academics/api/clients/1
Accept: application/json


### REQUEST JWT TOKEN
POST http://localhost:8080/academics/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "nif": "1",
  "password": "password"
}


